config/routes.rb
Rails.application.routes.draw do

  resources :aminas
  namespace :api, defaults: {format: 'json'} do
    scope :v1 do
      resources :reports
      resources :aminas
    end
  end 

  root to: 'pages#index' 

  get 'logout', to: 'users#logout', as: 'logout'
  
  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/terms'

  get 'pages/mission'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  resources :reports
  resources :report_categories
  devise_for :users
  resources :users 


# Avatar routes
get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
  app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
}, as: :avatar



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amina.rb
class Amina < ApplicationRecord
end

app/controllers/aminas_controller.rb
class AminasController < ApplicationController
  before_action :set_amina, only: [:show, :edit, :update, :destroy]

  # GET /aminas
  # GET /aminas.json
  def index
    @aminas = Amina.all
  end

  # GET /aminas/1
  # GET /aminas/1.json
  def show
  end

  # GET /aminas/new
  def new
    @amina = Amina.new
  end

  # GET /aminas/1/edit
  def edit
  end

  # POST /aminas
  # POST /aminas.json
  def create
    @amina = Amina.new(amina_params)

    respond_to do |format|
      if @amina.save
        format.html { redirect_to @amina, notice: 'Amina was successfully created.' }
        format.json { render :show, status: :created, location: @amina }
      else
        format.html { render :new }
        format.json { render json: @amina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aminas/1
  # PATCH/PUT /aminas/1.json
  def update
    respond_to do |format|
      if @amina.update(amina_params)
        format.html { redirect_to @amina, notice: 'Amina was successfully updated.' }
        format.json { render :show, status: :ok, location: @amina }
      else
        format.html { render :edit }
        format.json { render json: @amina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aminas/1
  # DELETE /aminas/1.json
  def destroy
    @amina.destroy
    respond_to do |format|
      format.html { redirect_to aminas_url, notice: 'Amina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amina
      @amina = Amina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amina_params
      params.require(:amina).permit(:email)
    end
end

app/controllers/api/aminas_controller.rb
class Api::AminasController < ApplicationController
  before_action :set_amina, only: [:show, :edit, :update, :destroy]

  # GET /aminas
  # GET /aminas.json
  def index
    @aminas = Amina.all
  end

  # GET /aminas/1
  # GET /aminas/1.json
  def show
  end

  # GET /aminas/new
  def new
    @amina = Amina.new
  end

  # GET /aminas/1/edit
  def edit
  end

  # POST /aminas
  # POST /aminas.json
  def create
    @amina = Amina.new(amina_params)

    respond_to do |format|
      if @amina.save
        format.html { redirect_to @amina, notice: 'Amina was successfully created.' }
        format.json { render :show, status: :created, location: @amina }
      else
        format.html { render :new }
        format.json { render json: @amina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aminas/1
  # PATCH/PUT /aminas/1.json
  def update
    respond_to do |format|
      if @amina.update(amina_params)
        format.html { redirect_to @amina, notice: 'Amina was successfully updated.' }
        format.json { render :show, status: :ok, location: @amina }
      else
        format.html { render :edit }
        format.json { render json: @amina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aminas/1
  # DELETE /aminas/1.json
  def destroy
    @amina.destroy
    respond_to do |format|
      format.html { redirect_to aminas_url, notice: 'Amina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amina
      @amina = Amina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amina_params
      params.require(:amina).permit(:email)
    end
end

app/helpers/aminas_helper.rb
module AminasHelper
end

app/views/aminas/_form.html.erb
<%= form_for(amina) do |f| %>
  <% if amina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amina.errors.count, "error") %> prohibited this amina from being saved:</h2>

      <ul>
      <% amina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aminas/edit.html.erb
<h1>Editing Amina</h1>

<%= render 'form', amina: @amina %>

<%= link_to 'Show', @amina %> |
<%= link_to 'Back', aminas_path %>

app/views/aminas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aminas</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aminas.each do |amina| %>
      <tr>
        <td><%= amina.email %></td>
        <td><%= link_to 'Show', amina %></td>
        <td><%= link_to 'Edit', edit_amina_path(amina) %></td>
        <td><%= link_to 'Destroy', amina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amina', new_amina_path %>

app/views/aminas/new.html.erb
<h1>New Amina</h1>

<%= render 'form', amina: @amina %>

<%= link_to 'Back', aminas_path %>

app/views/aminas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @amina.email %>
</p>

<%= link_to 'Edit', edit_amina_path(@amina) %> |
<%= link_to 'Back', aminas_path %>