config/routes.rb
Rails.application.routes.draw do

  resources :aminas
  namespace :api, defaults: {format: 'json'} do
    scope :v1 do
      resources :reports
      resources :aminas
    end
  end 

  root to: 'pages#index' 

  get 'logout', to: 'users#logout', as: 'logout'
  
  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/terms'

  get 'pages/mission'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  resources :reports
  resources :report_categories
  devise_for :users
  resources :users 


# Avatar routes
get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
  app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
}, as: :avatar



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report_category.rb
class ReportCategory < ApplicationRecord
  has_many :reports
end

app/controllers/report_categories_controller.rb
class ReportCategoriesController < ApplicationController
  before_action :set_report_category, only: [:show, :edit, :update, :destroy]

  # GET /report_categories
  # GET /report_categories.json

  layout 'rep'
  
  def index
    @report_categories = ReportCategory.all
  end

  # GET /report_categories/1
  # GET /report_categories/1.json
  def show
  end

  # GET /report_categories/new
  def new
    @report_category = ReportCategory.new
  end

  # GET /report_categories/1/edit
  def edit
  end

  # POST /report_categories
  # POST /report_categories.json
  def create
    @report_category = ReportCategory.new(report_category_params)

    respond_to do |format|
      if @report_category.save
        format.html { redirect_to @report_category, notice: 'Report category was successfully created.' }
        format.json { render :show, status: :created, location: @report_category }
      else
        format.html { render :new }
        format.json { render json: @report_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /report_categories/1
  # PATCH/PUT /report_categories/1.json
  def update
    respond_to do |format|
      if @report_category.update(report_category_params)
        format.html { redirect_to @report_category, notice: 'Report category was successfully updated.' }
        format.json { render :show, status: :ok, location: @report_category }
      else
        format.html { render :edit }
        format.json { render json: @report_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_categories/1
  # DELETE /report_categories/1.json
  def destroy
    @report_category.destroy
    respond_to do |format|
      format.html { redirect_to report_categories_url, notice: 'Report category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report_category
      @report_category = ReportCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_category_params
      params.require(:report_category).permit(:name, :description)
    end
end

app/helpers/report_categories_helper.rb
module ReportCategoriesHelper
end

app/views/report_categories/_form.html.erb
<%= form_for(report_category) do |f| %>
  <% if report_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report_category.errors.count, "error") %> prohibited this report_category from being saved:</h2>

      <ul>
      <% report_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/report_categories/edit.html.erb
<h1>Editing Report Category</h1>

<%= render 'form', report_category: @report_category %>

<%= link_to 'Show', @report_category %> |
<%= link_to 'Back', report_categories_path %>

app/views/report_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Report Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @report_categories.each do |report_category| %>
      <tr>
        <td><%= report_category.name %></td>
        <td><%= report_category.description %></td>
        <td><%= link_to 'Show', report_category %></td>
        <td><%= link_to 'Edit', edit_report_category_path(report_category) %></td>
        <td><%= link_to 'Destroy', report_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report Category', new_report_category_path %>

app/views/report_categories/new.html.erb
<h1>New Report Category</h1>

<%= render 'form', report_category: @report_category %>

<%= link_to 'Back', report_categories_path %>

app/views/report_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @report_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report_category.description %>
</p>

<%= link_to 'Edit', edit_report_category_path(@report_category) %> |
<%= link_to 'Back', report_categories_path %>