config/routes.rb
Rails.application.routes.draw do

  resources :aminas
  namespace :api, defaults: {format: 'json'} do
    scope :v1 do
      resources :reports
      resources :aminas
    end
  end 

  root to: 'pages#index' 

  get 'logout', to: 'users#logout', as: 'logout'
  
  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/terms'

  get 'pages/mission'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  resources :reports
  resources :report_categories
  devise_for :users
  resources :users 


# Avatar routes
get "avatar/:size/:background/:text" => Dragonfly.app.endpoint { |params, app|
  app.generate(:initial_avatar, URI.unescape(params[:text]), { size: params[:size], background_color: params[:background] })
}, as: :avatar



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" >
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
  <head>
    <title>Feedintel</title>
    <%= csrf_meta_tags %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
<link rel="icon" type="image/png" href="../assets/img/favicon.png">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />



    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">



<link href="../assets/css/material-kit.minf066.css?v=2.1.0" rel="stylesheet" />



<link href="../assets/demo/vertical-nav.css" rel="stylesheet"/>



<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NKDMSK6');</script>
<!-- End Google Tag Manager -->





  </head>
    
  

       <body class="index-page sidebar-collapse">


      
      <!-- Extra details for Live View on GitHub Pages -->
      <!-- Google Tag Manager (noscript) -->

<!-- End Google Tag Manager (noscript) -->

      
      
        <nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg "  color-on-scroll="100"  id="sectionsNav">

    <div class="container">
        <div class="navbar-translate">
          
            <a class="navbar-brand" href="<%=root_path%>">
              <img src="http://oi63.tinypic.com/25f63bs.jpg"> </a>
          
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">

              

                <li class="dropdown nav-item">
                  <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                      <i class="material-icons">apps</i> about feedIntel
                  </a>
                  <div class="dropdown-menu dropdown-with-icons">
                    <a href="../index.html" class="dropdown-item">
                        <i class="material-icons">layers</i> our Team
                    </a>
                    <a href="../docs/2.0/getting-started/introduction.html" class="dropdown-item">
                        <i class="material-icons">content_paste</i> our Mission
                    </a>
                     <a href="../docs/2.0/getting-started/introduction.html" class="dropdown-item">
                        <i class="material-icons">content_paste</i> our Technology
                    </a>
                     <a href="../sections.html#contactus" class="dropdown-item">
                        <i class="material-icons">call</i> contact us
                    </a>
                  </div>
                </li>

                

                

                

                <li class="dropdown nav-item">
                  <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                      <i class="material-icons">view_day</i> Reporting
                  </a>

                 
                  <div class="dropdown-menu dropdown-with-icons">

                  	 <% if user_signed_in? %>

	                    <a href="<%=dashboard_path%>" class="dropdown-item">
	                        <i class="material-icons">dns</i> Dashboard
	                    </a>


	                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#reportsModal">
	                        <i class="material-icons">add_circle</i> submit Intel
	                    </a>
	                    <a href="#" class="dropdown-item">
	                        <i class="material-icons">list</i> Maps 
	                    </a>
                   
                     <% else %>

                     <a href="#" class="dropdown-item">
	                        <i class="material-icons">list</i> Maps 
	                    </a>


                   	 <% end %>


                   
                  </div>

                 


                   </li>
                  <% if signed_in? %>
                    <li class="button-container nav-item iframe-extern">
                        <a href="<%= user_path(current_user) %>" class="btn  btn-rose   btn-round btn-block">
                            <i class="material-icons"></i> Welcome <%= current_user.fullname.split(" ").first%>.<%=current_user.fullname.split(" ").second.chr %>
                        </a>
                    </li>
                    <li class="nav-item">


                    	<%= link_to "<i class='material-icons'>power</i>Logout".html_safe, logout_path, class: 'nav-link' %>
                    
                     
                    </li>
                  <% else %>
                     <li class="nav-item">
                      <a href="<%=new_user_session_path%>" class="nav-link" data-disable-with="processing ...">
                          <i class="material-icons">power</i> Login
                      </a>
                     
                    </li>

                  
                    <li class="button-container nav-item">
                        <a href="<%=new_user_registration_path%>" class="btn  btn-rose   btn-round btn-block" data-disable-with="Processing...">
                            <i class="material-icons"></i> Join Now
                        </a>
                    </li>
                  <% end %>
    

              
            </ul>
        </div>
    </div>
</nav>






        
        
  <%= yield %>
  
  
<footer class="footer" >
  <div class="container">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.creative-tim.com/">
             FeedIntel
          </a>
        </li>
        <li>
          <a href="https://creative-tim.com/presentation">
              About Us
          </a>
        </li>
        <li>
          <a href="http://blog.creative-tim.com/">
              Blog
          </a>
        </li>
        <li>
          <a href="https://www.creative-tim.com/license">
              Mission
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright float-right">
        &copy;
        <script>
            document.write(new Date().getFullYear())
        </script>, built with <i class="material-icons">favorite</i> in
        <a href="#" target="_blank">#NotAnotherNigerian</a> hackathon.
    </div>
  </div>
</footer>



</div>

        
      















<!--   Core JS Files   -->
<script src="../assets/js/core/jquery.min.js" type="text/javascript"></script>
<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="../assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>

<script src="../assets/js/plugins/moment.min.js"></script>

<!--  Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<script src="../assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>

<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="../assets/js/plugins/nouislider.min.js" type="text/javascript"></script><!--  Google Maps Plugin  -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

  <!--  Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <!-- 
  <script src="../assets/js/plugins/bootstrap-tagsinput.js"></script> -->
  <!--  Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="../assets/js/plugins/bootstrap-selectpicker.js" type="text/javascript"></script>

  <!--  Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="../assets/js/plugins/jasny-bootstrap.min.js" type="text/javascript"></script>

  <!--  Plugin for Small Gallery in Product Page -->
  <script src="../assets/js/plugins/jquery.flexisel.js" type="text/javascript"></script>

  <!-- Plugins for presentation and navigation  -->
  <script src="../assets/demo/modernizr.js" type="text/javascript"></script>
  <script src="../assets/demo/vertical-nav.js" type="text/javascript"></script>

  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>


<!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc --><script src="../assets/js/material-kit.minf066.js?v=2.1.0" type="text/javascript"></script>
  

<script>
  $(document).ready(function(){
    
    
    var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-46172202-1']);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
})();

    // Facebook Pixel Code Don't Delete
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','http://connect.facebook.net/en_US/fbevents.js');

try{
  fbq('init', '111649226022273');
  fbq('track', "PageView");

}catch(err) {
  console.log('Facebook Track Error:', err);
}

  });
</script>
<noscript>
  <img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=111649226022273&amp;ev=PageView&amp;noscript=1"
/>

</noscript>



  </body>
</html>

app/views/layouts/rep.html.erb
<!DOCTYPE html>
<html lang="en" >
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
  <head>
    <title>Feedintel</title>
    <%= csrf_meta_tags %>


<link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
<link rel="icon" type="image/png" href="../assets/img/favicon.png">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />



    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">



<link href="../assets/css/material-kit.minf066.css?v=2.1.0" rel="stylesheet" />



<link href="../assets/demo/vertical-nav.css" rel="stylesheet"/>







  </head>
    
  

       <body class="index-page sidebar-collapse">


      
      <!-- Extra details for Live View on GitHub Pages -->
      <!-- Google Tag Manager (noscript) -->

<!-- End Google Tag Manager (noscript) -->

      
      
        <nav class="navbar navbar-color-on-scroll navbar-transparent    fixed-top  navbar-expand-lg "  color-on-scroll="100"  id="sectionsNav">

    <div class="container">
        <div class="navbar-translate">
          
            <a class="navbar-brand" href="<%=root_path%>">
              <img src="http://oi63.tinypic.com/25f63bs.jpg"> </a>
          
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">

              

                <li class="dropdown nav-item">
                  <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                      <i class="material-icons">apps</i> about feedIntel
                  </a>
                  <div class="dropdown-menu dropdown-with-icons">
                    <a href="../index.html" class="dropdown-item">
                        <i class="material-icons">layers</i> our Team
                    </a>
                    <a href="../docs/2.0/getting-started/introduction.html" class="dropdown-item">
                        <i class="material-icons">content_paste</i> our Mission
                    </a>
                     <a href="../docs/2.0/getting-started/introduction.html" class="dropdown-item">
                        <i class="material-icons">content_paste</i> our Technology
                    </a>
                     <a href="../sections.html#contactus" class="dropdown-item">
                        <i class="material-icons">call</i> contact us
                    </a>
                  </div>
                </li>

                

                

                

                <li class="dropdown nav-item">
                  <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                      <i class="material-icons">view_day</i> Reporting
                  </a>
                  <div class="dropdown-menu dropdown-with-icons">
                    <a href="../sections.html#headers" class="dropdown-item">
                        <i class="material-icons">dns</i> view Reports
                    </a>

                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#reportsModal">
                        <i class="material-icons">add_circle</i> submit Intel
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="material-icons">list</i> Maps 
                    </a>
                   
                   
                  </div>

                   </li>
                  <% if signed_in? %>
                    <li class="button-container nav-item iframe-extern">
                        <a href="<%= user_path(current_user) %>" class="btn  btn-rose   btn-round btn-block">
                            <i class="material-icons"></i> Welcome <%= current_user.email%>
                        </a>
                    </li>
                    <li class="nav-item">


                    	<%= link_to "<i class='material-icons'>power</i>Logout".html_safe, logout_path, class: 'nav-link' %>
                    
                     
                    </li>
                  <% else %>
                     <li class="nav-item">
                      <a href="<%=new_user_session_path%>" class="nav-link" data-disable-with="processing ...">
                          <i class="material-icons">power</i> Login
                      </a>
                     
                    </li>

                  
                    <li class="button-container nav-item">
                        <a href="<%=new_user_registration_path%>" class="btn  btn-rose   btn-round btn-block" data-disable-with="Processing...">
                            <i class="material-icons"></i> Join Now
                        </a>
                    </li>
                  <% end %>
    

              
            </ul>
        </div>
    </div>
</nav>



    <div class="page-header header-filter clear-filter" data-parallax="true" style="background-image: url('assets/img/bg0n-new.png');">
    <div class="container">
        <div class="row">

          Page

        </div>
    </div>
</div>






<div class="main main-raised">
  
    <div class="section section-basic">
        <div class="container">
            <!-- <div class="title">
              <h2>Basic</h2>
            </div> -->


            <%=yield%>


        </div>


   


  

    </div>
</div>




 
 





  
<footer class="footer" >
  <div class="container">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.creative-tim.com/">
             FeedIntel
          </a>
        </li>
        <li>
          <a href="https://creative-tim.com/presentation">
              About Us
          </a>
        </li>
        <li>
          <a href="http://blog.creative-tim.com/">
              Blog
          </a>
        </li>
        <li>
          <a href="https://www.creative-tim.com/license">
              Mission
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright float-right">
        &copy;
        <script>
            document.write(new Date().getFullYear())
        </script>, built with <i class="material-icons">favorite</i> in
        <a href="#" target="_blank">#NotAnotherNigerian</a> hackathon.
    </div>
  </div>
</footer>



</div>

        
      















<!--   Core JS Files   -->
<script src="../assets/js/core/jquery.min.js" type="text/javascript"></script>
<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="../assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>

<script src="../assets/js/plugins/moment.min.js"></script>

<!--  Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<script src="../assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>

<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="../assets/js/plugins/nouislider.min.js" type="text/javascript"></script><!--  Google Maps Plugin  -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

  <!--  Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <!-- 
  <script src="../assets/js/plugins/bootstrap-tagsinput.js"></script> -->
  <!--  Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="../assets/js/plugins/bootstrap-selectpicker.js" type="text/javascript"></script>

  <!--  Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="../assets/js/plugins/jasny-bootstrap.min.js" type="text/javascript"></script>

  <!--  Plugin for Small Gallery in Product Page -->
  <script src="../assets/js/plugins/jquery.flexisel.js" type="text/javascript"></script>

  <!-- Plugins for presentation and navigation  -->
  <script src="../assets/demo/modernizr.js" type="text/javascript"></script>
  <script src="../assets/demo/vertical-nav.js" type="text/javascript"></script>

  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>


<!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc --><script src="../assets/js/material-kit.minf066.js?v=2.1.0" type="text/javascript"></script>
  

<script>
  $(document).ready(function(){
    
    
    var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-46172202-1']);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
})();

    // Facebook Pixel Code Don't Delete
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','http://connect.facebook.net/en_US/fbevents.js');

try{
  fbq('init', '111649226022273');
  fbq('track', "PageView");

}catch(err) {
  console.log('Facebook Track Error:', err);
}

  });
</script>
<noscript>
  <img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=111649226022273&amp;ev=PageView&amp;noscript=1"
/>

</noscript>



  </body>
</html>